//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Media.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Media.Resources.ProjectResources", typeof(ProjectResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все объекты.
        /// </summary>
        public static string AllTreeControlTooltip {
            get {
                return ResourceManager.GetString("AllTreeControlTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string BackTreeControlTooltip {
            get {
                return ResourceManager.GetString("BackTreeControlTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка данных.
        /// </summary>
        public static string BusyContent {
            get {
                return ResourceManager.GetString("BusyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться.
        /// </summary>
        public static string buTransit {
            get {
                return ResourceManager.GetString("buTransit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        public static string CancelButtonHistory {
            get {
                return ResourceManager.GetString("CancelButtonHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить.
        /// </summary>
        public static string cancelButtonPasport {
            get {
                return ResourceManager.GetString("cancelButtonPasport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать детали.
        /// </summary>
        public static string checkDetal {
            get {
                return ResourceManager.GetString("checkDetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользовательская ошибка.
        /// </summary>
        public static string CheckLink0 {
            get {
                return ResourceManager.GetString("CheckLink0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нельзя добавить связь сверх разрешенного кардинальностью..
        /// </summary>
        public static string CheckLink1 {
            get {
                return ResourceManager.GetString("CheckLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объекты не могут организовать связь &quot;часть-содержит&quot;..
        /// </summary>
        public static string CheckLink2 {
            get {
                return ResourceManager.GetString("CheckLink2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удается определить сущность для родительского ообъекта..
        /// </summary>
        public static string CheckLink3 {
            get {
                return ResourceManager.GetString("CheckLink3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет прав на создание данного объекта.
        /// </summary>
        public static string CheckLink4 {
            get {
                return ResourceManager.GetString("CheckLink4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перечень связанных объектов.
        /// </summary>
        public static string ChildLinkObjAll {
            get {
                return ResourceManager.GetString("ChildLinkObjAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Километраж А.
        /// </summary>
        public static string Childpriv {
            get {
                return ResourceManager.GetString("Childpriv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Километраж B.
        /// </summary>
        public static string ChildprivB {
            get {
                return ResourceManager.GetString("ChildprivB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на , м.
        /// </summary>
        public static string ChildprivM {
            get {
                return ResourceManager.GetString("ChildprivM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дочерние объекты.
        /// </summary>
        public static string childTabItem {
            get {
                return ResourceManager.GetString("childTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание.
        /// </summary>
        public static string ChildWindowAttantion {
            get {
                return ResourceManager.GetString("ChildWindowAttantion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление, редактирование словарей.
        /// </summary>
        public static string ChildWindowDictTitle {
            get {
                return ResourceManager.GetString("ChildWindowDictTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотр истории изменения в паспорте.
        /// </summary>
        public static string ChildWindowHistoriPassportTitle {
            get {
                return ResourceManager.GetString("ChildWindowHistoriPassportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string ChildWindowLinkObj {
            get {
                return ResourceManager.GetString("ChildWindowLinkObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название экземпляра объекта связи.
        /// </summary>
        public static string ChildWindowLinkObjGridViewObjName {
            get {
                return ResourceManager.GetString("ChildWindowLinkObjGridViewObjName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление связанного объекта.
        /// </summary>
        public static string ChildWindowLinkObjTitle {
            get {
                return ResourceManager.GetString("ChildWindowLinkObjTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать дату.
        /// </summary>
        public static string ControlDateTime {
            get {
                return ResourceManager.GetString("ControlDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всего:.
        /// </summary>
        public static string CountFunctionGrid {
            get {
                return ResourceManager.GetString("CountFunctionGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные.
        /// </summary>
        public static string dataTabItem {
            get {
                return ResourceManager.GetString("dataTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить связь.
        /// </summary>
        public static string DeleteRelationButtonToolTip {
            get {
                return ResourceManager.GetString("DeleteRelationButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Не определено&gt;.
        /// </summary>
        public static string DictDataFiltr {
            get {
                return ResourceManager.GetString("DictDataFiltr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Документы.
        /// </summary>
        public static string documentTabItem {
            get {
                return ResourceManager.GetString("documentTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        public static string editButtonPasport {
            get {
                return ResourceManager.GetString("editButtonPasport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать дату.
        /// </summary>
        public static string EnterDate {
            get {
                return ResourceManager.GetString("EnterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка сохранения паспорта.
        /// </summary>
        public static string ErrSavePasportMessage {
            get {
                return ResourceManager.GetString("ErrSavePasportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить новый медиаматериал.
        /// </summary>
        public static string ExpanderAddNewMedia {
            get {
                return ResourceManager.GetString("ExpanderAddNewMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные.
        /// </summary>
        public static string exportGridDate {
            get {
                return ResourceManager.GetString("exportGridDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        public static string exportGridName {
            get {
                return ResourceManager.GetString("exportGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заводской паспорт.
        /// </summary>
        public static string factoryPassportTabItem {
            get {
                return ResourceManager.GetString("factoryPassportTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать файл.
        /// </summary>
        public static string FileUploadAddFileButon {
            get {
                return ResourceManager.GetString("FileUploadAddFileButon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить.
        /// </summary>
        public static string FileUploadClearButton {
            get {
                return ResourceManager.GetString("FileUploadClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коментарий к файлу.
        /// </summary>
        public static string FileUploadComment {
            get {
                return ResourceManager.GetString("FileUploadComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить.
        /// </summary>
        public static string FileUploadLoadButton {
            get {
                return ResourceManager.GetString("FileUploadLoadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на одинаковое название файлов.
        /// </summary>
        public static string FileUploadMessage {
            get {
                return ResourceManager.GetString("FileUploadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название файла:.
        /// </summary>
        public static string FileUploadNameFile {
            get {
                return ResourceManager.GetString("FileUploadNameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прогресс.
        /// </summary>
        public static string FileUploadProgress {
            get {
                return ResourceManager.GetString("FileUploadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер.
        /// </summary>
        public static string FileUploadSize {
            get {
                return ResourceManager.GetString("FileUploadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string FileUploadStatus {
            get {
                return ResourceManager.GetString("FileUploadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип файла:.
        /// </summary>
        public static string FileUploadTypeFile {
            get {
                return ResourceManager.GetString("FileUploadTypeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вперед.
        /// </summary>
        public static string ForwardTreeControlTooltip {
            get {
                return ResourceManager.GetString("ForwardTreeControlTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название типа объекта.
        /// </summary>
        public static string gridAllObj {
            get {
                return ResourceManager.GetString("gridAllObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить объект связи.
        /// </summary>
        public static string GridControlAddRelationButtonToolTip {
            get {
                return ResourceManager.GetString("GridControlAddRelationButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать.
        /// </summary>
        public static string GridControlColumn {
            get {
                return ResourceManager.GetString("GridControlColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить связь объекта.
        /// </summary>
        public static string GridControlDeleteRelationButtonToolTip {
            get {
                return ResourceManager.GetString("GridControlDeleteRelationButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связи объекта.
        /// </summary>
        public static string GridControlLinkObj {
            get {
                return ResourceManager.GetString("GridControlLinkObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не выбран в таблице объект удаления.
        /// </summary>
        public static string GridControlMessage {
            get {
                return ResourceManager.GetString("GridControlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить связь  с объектом.
        /// </summary>
        public static string GridControlMessageDel {
            get {
                return ResourceManager.GetString("GridControlMessageDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение удаления.
        /// </summary>
        public static string GridControlMessageTitle {
            get {
                return ResourceManager.GetString("GridControlMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название типа объекта.
        /// </summary>
        public static string GridRelationNameEntity {
            get {
                return ResourceManager.GetString("GridRelationNameEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название экземпляра объекта связи.
        /// </summary>
        public static string GridRelationNameObj {
            get {
                return ResourceManager.GetString("GridRelationNameObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название атрибута.
        /// </summary>
        public static string GridViewCFieldName {
            get {
                return ResourceManager.GetString("GridViewCFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить фильтр.
        /// </summary>
        public static string GridViewClearFilter {
            get {
                return ResourceManager.GetString("GridViewClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение.
        /// </summary>
        public static string GridViewColdval {
            get {
                return ResourceManager.GetString("GridViewColdval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автор изменений.
        /// </summary>
        public static string GridViewCUser {
            get {
                return ResourceManager.GetString("GridViewCUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата/время.
        /// </summary>
        public static string GridViewDoperationtime {
            get {
                return ResourceManager.GetString("GridViewDoperationtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр.
        /// </summary>
        public static string GridViewFilter {
            get {
                return ResourceManager.GetString("GridViewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на И.
        /// </summary>
        public static string GridViewFilterAnd {
            get {
                return ResourceManager.GetString("GridViewFilterAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на содержит.
        /// </summary>
        public static string GridViewFilterContains {
            get {
                return ResourceManager.GetString("GridViewFilterContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать дату.
        /// </summary>
        public static string GridViewFilterDateTime {
            get {
                return ResourceManager.GetString("GridViewFilterDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [нет данных].
        /// </summary>
        public static string GridViewFilterDistinctValueNull {
            get {
                return ResourceManager.GetString("GridViewFilterDistinctValueNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [нет данных].
        /// </summary>
        public static string GridViewFilterDistinctValueStringEmpty {
            get {
                return ResourceManager.GetString("GridViewFilterDistinctValueStringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не содержит.
        /// </summary>
        public static string GridViewFilterDoesNotContain {
            get {
                return ResourceManager.GetString("GridViewFilterDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на заканчивая на.
        /// </summary>
        public static string GridViewFilterEndsWith {
            get {
                return ResourceManager.GetString("GridViewFilterEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на содержит в.
        /// </summary>
        public static string GridViewFilterIsContainedIn {
            get {
                return ResourceManager.GetString("GridViewFilterIsContainedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пусто.
        /// </summary>
        public static string GridViewFilterIsEmpty {
            get {
                return ResourceManager.GetString("GridViewFilterIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на равно.
        /// </summary>
        public static string GridViewFilterIsEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на больше, чем.
        /// </summary>
        public static string GridViewFilterIsGreaterThan {
            get {
                return ResourceManager.GetString("GridViewFilterIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на больше или равно.
        /// </summary>
        public static string GridViewFilterIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на меньше, чем.
        /// </summary>
        public static string GridViewFilterIsLessThan {
            get {
                return ResourceManager.GetString("GridViewFilterIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на меньше или равно.
        /// </summary>
        public static string GridViewFilterIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не содержит в.
        /// </summary>
        public static string GridViewFilterIsNotContainedIn {
            get {
                return ResourceManager.GetString("GridViewFilterIsNotContainedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не пусто.
        /// </summary>
        public static string GridViewFilterIsNotEmpty {
            get {
                return ResourceManager.GetString("GridViewFilterIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не равно.
        /// </summary>
        public static string GridViewFilterIsNotEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не нулл.
        /// </summary>
        public static string GridViewFilterIsNotNull {
            get {
                return ResourceManager.GetString("GridViewFilterIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на нулл.
        /// </summary>
        public static string GridViewFilterIsNull {
            get {
                return ResourceManager.GetString("GridViewFilterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Или.
        /// </summary>
        public static string GridViewFilterOr {
            get {
                return ResourceManager.GetString("GridViewFilterOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать все.
        /// </summary>
        public static string GridViewFilterSelectAll {
            get {
                return ResourceManager.GetString("GridViewFilterSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать строки, где значение....
        /// </summary>
        public static string GridViewFilterShowRowsWithValueThat {
            get {
                return ResourceManager.GetString("GridViewFilterShowRowsWithValueThat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на начиная с.
        /// </summary>
        public static string GridViewFilterStartsWith {
            get {
                return ResourceManager.GetString("GridViewFilterStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перенесите колонку для группировки.
        /// </summary>
        public static string GridViewGroupPanelText {
            get {
                return ResourceManager.GetString("GridViewGroupPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сгруппировано по: .
        /// </summary>
        public static string GridViewGroupPanelTopTextGrouped {
            get {
                return ResourceManager.GetString("GridViewGroupPanelTopTextGrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторить пароль.
        /// </summary>
        public static string HashControlTitleBox {
            get {
                return ResourceManager.GetString("HashControlTitleBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История изменения паспорта.
        /// </summary>
        public static string historiButton {
            get {
                return ResourceManager.GetString("historiButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string insertCurrentRecordDict {
            get {
                return ResourceManager.GetString("insertCurrentRecordDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ключ значения словаря.
        /// </summary>
        public static string KEYDICT {
            get {
                return ResourceManager.GetString("KEYDICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отобразить все связанные элементы....
        /// </summary>
        public static string LinkAll {
            get {
                return ResourceManager.GetString("LinkAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cкрыть полный перечень связанных элементов....
        /// </summary>
        public static string LinkAllHide {
            get {
                return ResourceManager.GetString("LinkAllHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список паспортов.
        /// </summary>
        public static string LinkButton {
            get {
                return ResourceManager.GetString("LinkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавьте горизонтальную связь....
        /// </summary>
        public static string LinkControlEditAdd {
            get {
                return ResourceManager.GetString("LinkControlEditAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связи объекта.
        /// </summary>
        public static string LinkTableTitle {
            get {
                return ResourceManager.GetString("LinkTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарии:.
        /// </summary>
        public static string mediaComment {
            get {
                return ResourceManager.GetString("mediaComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить медиаматериал?.
        /// </summary>
        public static string MediaDel {
            get {
                return ResourceManager.GetString("MediaDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить медиаматериал.
        /// </summary>
        public static string MediaDelToolTip {
            get {
                return ResourceManager.GetString("MediaDelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Медиаматериалы.
        /// </summary>
        public static string mediaTabItem {
            get {
                return ResourceManager.GetString("mediaTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест Привет!.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название объекта:.
        /// </summary>
        public static string nameEntityObj {
            get {
                return ResourceManager.GetString("nameEntityObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый паспорт.
        /// </summary>
        public static string NewPassport {
            get {
                return ResourceManager.GetString("NewPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать новую связь.
        /// </summary>
        public static string NewRelationButtonToolTip {
            get {
                return ResourceManager.GetString("NewRelationButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не выбран медиаматериал.
        /// </summary>
        public static string NoMedia {
            get {
                return ResourceManager.GetString("NoMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не выбран тип медиаматериала.
        /// </summary>
        public static string NoMediaType {
            get {
                return ResourceManager.GetString("NoMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Допустимы только  числа.
        /// </summary>
        public static string NumberExeption {
            get {
                return ResourceManager.GetString("NumberExeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет дочерних объектов.
        /// </summary>
        public static string PassportChild {
            get {
                return ResourceManager.GetString("PassportChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый.
        /// </summary>
        public static string PassportChildBuNuwChild {
            get {
                return ResourceManager.GetString("PassportChildBuNuwChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить паспорт дочерних объектов вместе со связями?.
        /// </summary>
        public static string PassportChildTitleBox {
            get {
                return ResourceManager.GetString("PassportChildTitleBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не выбран в таблице объект удаления..
        /// </summary>
        public static string PassportViewAttantion {
            get {
                return ResourceManager.GetString("PassportViewAttantion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все объекты.
        /// </summary>
        public static string PassportViewNameEntityObj {
            get {
                return ResourceManager.GetString("PassportViewNameEntityObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить объект.
        /// </summary>
        public static string PassportViewPopupWindow {
            get {
                return ResourceManager.GetString("PassportViewPopupWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на вместе со связями?.
        /// </summary>
        public static string PassportViewPopupWindow1 {
            get {
                return ResourceManager.GetString("PassportViewPopupWindow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        public static string photoAll {
            get {
                return ResourceManager.GetString("photoAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прочее.
        /// </summary>
        public static string photoOther {
            get {
                return ResourceManager.GetString("photoOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фотографии.
        /// </summary>
        public static string photoTabItem {
            get {
                return ResourceManager.GetString("photoTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Форматированная печать.
        /// </summary>
        public static string PrintButtonToolbar {
            get {
                return ResourceManager.GetString("PrintButtonToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите протяженный объект....
        /// </summary>
        public static string Priv1 {
            get {
                return ResourceManager.GetString("Priv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Точечная, линейная или полигональная привязка объекта.
        /// </summary>
        public static string Priv10P1 {
            get {
                return ResourceManager.GetString("Priv10P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на без связи с газопроводами.
        /// </summary>
        public static string Priv10P2 {
            get {
                return ResourceManager.GetString("Priv10P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Точечная привязка объекта.
        /// </summary>
        public static string Priv1P1 {
            get {
                return ResourceManager.GetString("Priv1P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на на оси собственного газопровода.
        /// </summary>
        public static string Priv1P2 {
            get {
                return ResourceManager.GetString("Priv1P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите геодезический километраж....
        /// </summary>
        public static string Priv2 {
            get {
                return ResourceManager.GetString("Priv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на вне оси собственного газопровода.
        /// </summary>
        public static string Priv2P2 {
            get {
                return ResourceManager.GetString("Priv2P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительно.
        /// </summary>
        public static string Priv3 {
            get {
                return ResourceManager.GetString("Priv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Линейная привязка объекта.
        /// </summary>
        public static string Priv3P1 {
            get {
                return ResourceManager.GetString("Priv3P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите широту WGS....
        /// </summary>
        public static string Priv4 {
            get {
                return ResourceManager.GetString("Priv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на вне осей всех газопроводов коридора.
        /// </summary>
        public static string Priv5P2 {
            get {
                return ResourceManager.GetString("Priv5P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (широта и долгота).
        /// </summary>
        public static string Priv7 {
            get {
                return ResourceManager.GetString("Priv7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Широта и долгота 1.
        /// </summary>
        public static string Priv71 {
            get {
                return ResourceManager.GetString("Priv71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Широта и долгота 2.
        /// </summary>
        public static string Priv72 {
            get {
                return ResourceManager.GetString("Priv72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Широта и долгота 3.
        /// </summary>
        public static string Priv73 {
            get {
                return ResourceManager.GetString("Priv73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Широта и долгота 4.
        /// </summary>
        public static string Priv74 {
            get {
                return ResourceManager.GetString("Priv74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на без связи с газопроводами.
        /// </summary>
        public static string Priv7P2 {
            get {
                return ResourceManager.GetString("Priv7P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ход газа.
        /// </summary>
        public static string Priv8 {
            get {
                return ResourceManager.GetString("Priv8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на на осях двух газопроводов коридора.
        /// </summary>
        public static string Priv8P2 {
            get {
                return ResourceManager.GetString("Priv8P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на МГ, Нитка.
        /// </summary>
        public static string Priv9 {
            get {
                return ResourceManager.GetString("Priv9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на МГ, Нитка 1.
        /// </summary>
        public static string Priv9A {
            get {
                return ResourceManager.GetString("Priv9A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на МГ, Нитка 2.
        /// </summary>
        public static string Priv9B {
            get {
                return ResourceManager.GetString("Priv9B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на МГ, Нитка N.
        /// </summary>
        public static string Priv9C {
            get {
                return ResourceManager.GetString("Priv9C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ,˚.
        /// </summary>
        public static string Priv9Gr {
            get {
                return ResourceManager.GetString("Priv9Gr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на на осях нескольких газопроводов.
        /// </summary>
        public static string Priv9P2 {
            get {
                return ResourceManager.GetString("Priv9P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка.
        /// </summary>
        public static string PrivControl {
            get {
                return ResourceManager.GetString("PrivControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить привязку?.
        /// </summary>
        public static string PrivControlDelete {
            get {
                return ResourceManager.GetString("PrivControlDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавьте привязку....
        /// </summary>
        public static string PrivControlEditAdd {
            get {
                return ResourceManager.GetString("PrivControlEditAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка объекта.
        /// </summary>
        public static string PrivControlLinkTableWindowTitle {
            get {
                return ResourceManager.GetString("PrivControlLinkTableWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на слева.
        /// </summary>
        public static string PrivDistLeft {
            get {
                return ResourceManager.GetString("PrivDistLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на справа.
        /// </summary>
        public static string PrivDistRigth {
            get {
                return ResourceManager.GetString("PrivDistRigth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите расстояние до газопровода....
        /// </summary>
        public static string PrivDistTxt {
            get {
                return ResourceManager.GetString("PrivDistTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Долгота,˚.
        /// </summary>
        public static string PrivDolg {
            get {
                return ResourceManager.GetString("PrivDolg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Долгота.
        /// </summary>
        public static string PrivDolg1 {
            get {
                return ResourceManager.GetString("PrivDolg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите долготу WGS....
        /// </summary>
        public static string PrivDolg2 {
            get {
                return ResourceManager.GetString("PrivDolg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Долгота A,˚.
        /// </summary>
        public static string PrivDolgA {
            get {
                return ResourceManager.GetString("PrivDolgA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Долгота A.
        /// </summary>
        public static string PrivDolgA1 {
            get {
                return ResourceManager.GetString("PrivDolgA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ведите начальную долготу WGS....
        /// </summary>
        public static string PrivDolgATxt {
            get {
                return ResourceManager.GetString("PrivDolgATxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Долгота B,˚.
        /// </summary>
        public static string PrivDolgB {
            get {
                return ResourceManager.GetString("PrivDolgB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Долгота B.
        /// </summary>
        public static string PrivDolgB1 {
            get {
                return ResourceManager.GetString("PrivDolgB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ведите конечную долготу WGS....
        /// </summary>
        public static string PrivDolgBTxt {
            get {
                return ResourceManager.GetString("PrivDolgBTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начало.
        /// </summary>
        public static string PrivGbBegin {
            get {
                return ResourceManager.GetString("PrivGbBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Окончание.
        /// </summary>
        public static string PrivGbEnd {
            get {
                return ResourceManager.GetString("PrivGbEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ,˚.
        /// </summary>
        public static string PrivGr {
            get {
                return ResourceManager.GetString("PrivGr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Километраж, м.
        /// </summary>
        public static string PrivKm {
            get {
                return ResourceManager.GetString("PrivKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на , м.
        /// </summary>
        public static string PrivKm9m {
            get {
                return ResourceManager.GetString("PrivKm9m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Километраж А, м.
        /// </summary>
        public static string PrivKmA {
            get {
                return ResourceManager.GetString("PrivKmA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Километраж А1, м.
        /// </summary>
        public static string PrivKmA1 {
            get {
                return ResourceManager.GetString("PrivKmA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Километраж А2, м.
        /// </summary>
        public static string PrivKmA2 {
            get {
                return ResourceManager.GetString("PrivKmA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Километраж А.
        /// </summary>
        public static string PrivKmA9 {
            get {
                return ResourceManager.GetString("PrivKmA9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите километраж начала объекта....
        /// </summary>
        public static string PrivKmATxt {
            get {
                return ResourceManager.GetString("PrivKmATxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Километраж B, м.
        /// </summary>
        public static string PrivKmB {
            get {
                return ResourceManager.GetString("PrivKmB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Километраж B1, м.
        /// </summary>
        public static string PrivKmB1 {
            get {
                return ResourceManager.GetString("PrivKmB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Километраж B2, м.
        /// </summary>
        public static string PrivKmB2 {
            get {
                return ResourceManager.GetString("PrivKmB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Километраж В.
        /// </summary>
        public static string PrivKmB9 {
            get {
                return ResourceManager.GetString("PrivKmB9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите километраж конца объекта....
        /// </summary>
        public static string PrivKmBTxt {
            get {
                return ResourceManager.GetString("PrivKmBTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Км геод., м.
        /// </summary>
        public static string PrivKmGeod {
            get {
                return ResourceManager.GetString("PrivKmGeod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Координаты.
        /// </summary>
        public static string PrivKoord {
            get {
                return ResourceManager.GetString("PrivKoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расположение.
        /// </summary>
        public static string PrivLocation {
            get {
                return ResourceManager.GetString("PrivLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cлева.
        /// </summary>
        public static string PrivRbLeft {
            get {
                return ResourceManager.GetString("PrivRbLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cправа.
        /// </summary>
        public static string PrivRbRight {
            get {
                return ResourceManager.GetString("PrivRbRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать МГ....
        /// </summary>
        public static string PrivSelectMg {
            get {
                return ResourceManager.GetString("PrivSelectMg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Широта,˚.
        /// </summary>
        public static string PrivShirot {
            get {
                return ResourceManager.GetString("PrivShirot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Широта.
        /// </summary>
        public static string PrivShirot1 {
            get {
                return ResourceManager.GetString("PrivShirot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ведите широту WGS....
        /// </summary>
        public static string PrivShirot2 {
            get {
                return ResourceManager.GetString("PrivShirot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Широта A,˚.
        /// </summary>
        public static string PrivShirotA {
            get {
                return ResourceManager.GetString("PrivShirotA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Широта A.
        /// </summary>
        public static string PrivShirotA1 {
            get {
                return ResourceManager.GetString("PrivShirotA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ведите начальную широту WGS....
        /// </summary>
        public static string PrivShirotATxt {
            get {
                return ResourceManager.GetString("PrivShirotATxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Широта B,˚.
        /// </summary>
        public static string PrivShirotB {
            get {
                return ResourceManager.GetString("PrivShirotB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Широта B.
        /// </summary>
        public static string PrivShirotB1 {
            get {
                return ResourceManager.GetString("PrivShirotB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ведите конечную широту WGS....
        /// </summary>
        public static string PrivShirotBTxt {
            get {
                return ResourceManager.GetString("PrivShirotBTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расстояние, м.
        /// </summary>
        public static string PrivTbKm_ist {
            get {
                return ResourceManager.GetString("PrivTbKm_ist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расстояние A, м.
        /// </summary>
        public static string PrivTbKm_istA {
            get {
                return ResourceManager.GetString("PrivTbKm_istA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расстояние B, м.
        /// </summary>
        public static string PrivTbKm_istB {
            get {
                return ResourceManager.GetString("PrivTbKm_istB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка.
        /// </summary>
        public static string PrivTitle {
            get {
                return ResourceManager.GetString("PrivTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка создания привязки!.
        /// </summary>
        public static string PrivTitleBoxErr {
            get {
                return ResourceManager.GetString("PrivTitleBoxErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не все поля заполнены!.
        /// </summary>
        public static string PrivTitleBoxErrField {
            get {
                return ResourceManager.GetString("PrivTitleBoxErrField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нить.
        /// </summary>
        public static string PrivTitleBoxN {
            get {
                return ResourceManager.GetString("PrivTitleBoxN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расположение.
        /// </summary>
        public static string PrivTxtKm_Raspol {
            get {
                return ResourceManager.GetString("PrivTxtKm_Raspol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на МГ.
        /// </summary>
        public static string PtivTitleBoxM {
            get {
                return ResourceManager.GetString("PtivTitleBoxM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на из.
        /// </summary>
        public static string RadDataPagerOf {
            get {
                return ResourceManager.GetString("RadDataPagerOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страница.
        /// </summary>
        public static string RadDataPagerPage {
            get {
                return ResourceManager.GetString("RadDataPagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string saveButtonPasport {
            get {
                return ResourceManager.GetString("saveButtonPasport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить медиаматериал на диск.
        /// </summary>
        public static string saveMediaOnDisk {
            get {
                return ResourceManager.GetString("saveMediaOnDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Схемы.
        /// </summary>
        public static string shemaTabItem {
            get {
                return ResourceManager.GetString("shemaTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет данных..
        /// </summary>
        public static string TextBlockHistory {
            get {
                return ResourceManager.GetString("TextBlockHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение :.
        /// </summary>
        public static string TextBlockZnachDict {
            get {
                return ResourceManager.GetString("TextBlockZnachDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Словарь номер :.
        /// </summary>
        public static string textNameDict {
            get {
                return ResourceManager.GetString("textNameDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название словаря.
        /// </summary>
        public static string TextNameDict2 {
            get {
                return ResourceManager.GetString("TextNameDict2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string ToolTipDeletePasport {
            get {
                return ResourceManager.GetString("ToolTipDeletePasport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить в .xls.
        /// </summary>
        public static string ToolTipExelPasport {
            get {
                return ResourceManager.GetString("ToolTipExelPasport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помощь.
        /// </summary>
        public static string ToolTipHelpPasport {
            get {
                return ResourceManager.GetString("ToolTipHelpPasport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать новый паспорт.
        /// </summary>
        public static string ToolTipNewPasport {
            get {
                return ResourceManager.GetString("ToolTipNewPasport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить в .doc.
        /// </summary>
        public static string ToolTipWordPasport {
            get {
                return ResourceManager.GetString("ToolTipWordPasport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список.
        /// </summary>
        public static string TreeControlTabItem {
            get {
                return ResourceManager.GetString("TreeControlTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дерево.
        /// </summary>
        public static string TreeControlTabItemTree {
            get {
                return ResourceManager.GetString("TreeControlTabItemTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить дерево.
        /// </summary>
        public static string TreeControlTooltip {
            get {
                return ResourceManager.GetString("TreeControlTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать ветку дерева.
        /// </summary>
        public static string TreeControlTooltipCopy {
            get {
                return ResourceManager.GetString("TreeControlTooltipCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить файлы.
        /// </summary>
        public static string UploadBrowse {
            get {
                return ResourceManager.GetString("UploadBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить файлы.
        /// </summary>
        public static string UploadBrowseAppend {
            get {
                return ResourceManager.GetString("UploadBrowseAppend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер буффера слишком большой..
        /// </summary>
        public static string UploadBufferSizeSoBig {
            get {
                return ResourceManager.GetString("UploadBufferSizeSoBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string UploadCancel {
            get {
                return ResourceManager.GetString("UploadCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите файлы для загрузки.
        /// </summary>
        public static string UploadCaptionSelect {
            get {
                return ResourceManager.GetString("UploadCaptionSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранные файлы::.
        /// </summary>
        public static string UploadCaptionSelected {
            get {
                return ResourceManager.GetString("UploadCaptionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка завершена.
        /// </summary>
        public static string UploadCaptionUploaded {
            get {
                return ResourceManager.GetString("UploadCaptionUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка....
        /// </summary>
        public static string UploadCaptionUploading {
            get {
                return ResourceManager.GetString("UploadCaptionUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарий к добавленным файлам.
        /// </summary>
        public static string UploadComment {
            get {
                return ResourceManager.GetString("UploadComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перетащите файлы для загрузки.
        /// </summary>
        public static string UploadDrag {
            get {
                return ResourceManager.GetString("UploadDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление новых файлов.
        /// </summary>
        public static string UploadFiles {
            get {
                return ResourceManager.GetString("UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обоаботчик не найден или обработчик с ошибкой.
        /// </summary>
        public static string UploadHandlerNotFoundOrFailed {
            get {
                return ResourceManager.GetString("UploadHandlerNotFoundOrFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итем удален..
        /// </summary>
        public static string UploadItemDismissed {
            get {
                return ResourceManager.GetString("UploadItemDismissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пауза.
        /// </summary>
        public static string UploadPause {
            get {
                return ResourceManager.GetString("UploadPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некоторые из выбранных файлов ограничены:.
        /// </summary>
        public static string UploadRestriction {
            get {
                return ResourceManager.GetString("UploadRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальное количество загруженных файлов;.
        /// </summary>
        public static string UploadRestrictionCount {
            get {
                return ResourceManager.GetString("UploadRestrictionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальный размер файла;.
        /// </summary>
        public static string UploadRestrictionSize {
            get {
                return ResourceManager.GetString("UploadRestrictionSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общий размер всех загруженных файлов;.
        /// </summary>
        public static string UploadRestrictionTotalSize {
            get {
                return ResourceManager.GetString("UploadRestrictionTotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итог.
        /// </summary>
        public static string UploadResume {
            get {
                return ResourceManager.GetString("UploadResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всего:.
        /// </summary>
        public static string UploadTotal {
            get {
                return ResourceManager.GetString("UploadTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестная ошибка!.
        /// </summary>
        public static string UploadUnknownError {
            get {
                return ResourceManager.GetString("UploadUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить.
        /// </summary>
        public static string UploadUpload {
            get {
                return ResourceManager.GetString("UploadUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверная ссылка . Пожалуйста, убедитесь, что URL правильный!.
        /// </summary>
        public static string UploadUploadServiceUrlInvalidPropertyValue {
            get {
                return ResourceManager.GetString("UploadUploadServiceUrlInvalidPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не установлены свойства на UploadServiceUrl .
        /// </summary>
        public static string UploadUploadServiceUrlSetProperty {
            get {
                return ResourceManager.GetString("UploadUploadServiceUrlSetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение словаря.
        /// </summary>
        public static string VALUEDICT {
            get {
                return ResourceManager.GetString("VALUEDICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
